name: 03-building-blocks
on:
    workflow_dispatch:
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
    echo-good-bye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: |
                echo "I wil fail"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye!"
