name: 04-using-actions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Instal Dependencies
        run: npm ci
      - name : Printint Folders
        run: ls

    #01. Checkout the code from the repository
    #02. Install dep of our react application
    #03. Excute automated tests